<?php

namespace Database\Seeders;

use App\Models\User;
use Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Committee - Technology',
                'email' => 'tech@nplc.dev',
                'username' => 'tech',
                'password' => 'admin#tech',
                'role' => 'Super Admin',
                'permission' => [
                    'create_user', 'read_user', 'update_user', 'delete_user', 'restore_user',
                    'create_role', 'read_role', 'update_role', 'delete_role', 'restore_role',
                    'create_permission', 'read_permission', 'update_permission', 'delete_permission', 'restore_permission',
                    'set_game_timer', 'edit_game_timer', 'view_game_timer', 'start_game_timer', 'stop_game_timer', 'reset_game_timer',
                    'set_pos_timer', 'edit_pos_timer', 'view_pos_timer', 'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer',
                    'view_scoreboard', 'edit_scoreboard', 'set_scoreboard_Status', 'reset_scoreboard',
                    'add_story', 'edit_story', 'delete_story', 'restore_story', 'view_story',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'subtract_score', 'edit_score', 'view_score', 'reset_score',
                    'add_exp', 'subtract_exp', 'edit_exp', 'view_exp', 'reset_exp',
                    'add_coin', 'subtract_coin', 'edit_coin', 'view_coin', 'reset_coin',
                    'add_item', 'edit_item', 'view_item', 'delete_item', 'restore_item',
                    'add_equipment', 'subtract_equipment', 'edit_equipment', 'view_equipment', 'reset_equipment',
                ]
            ],
            [
                'name' => "Committee - Category 2",
                'email' => "cat2@nplc.dev",
                'username' => 'cat2',
                'password' => "admin#cat2",
                'role' => "Admin",
                'permission' => [
                    'set_game_timer', 'edit_game_timer', 'view_game_timer', 'start_game_timer', 'stop_game_timer', 'reset_game_timer',
                    'set_pos_timer', 'edit_pos_timer', 'view_pos_timer', 'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer',
                    'view_scoreboard',
                    'add_story', 'edit_story', 'delete_story', 'restore_story', 'view_story',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'subtract_score', 'edit_score', 'view_score', 'reset_score',
                    'add_exp', 'subtract_exp', 'edit_exp', 'view_exp', 'reset_exp',
                    'add_coin', 'subtract_coin', 'edit_coin', 'view_coin', 'reset_coin',
                    'add_item', 'edit_item', 'view_item', 'delete_item', 'restore_item',
                    'add_equipment', 'subtract_equipment', 'edit_equipment', 'view_equipment', 'reset_equipment',
                ]
            ],
            [
                'name' => "Committee",
                'email' => "committee@nplc.dev",
                'username' => 'committee',
                'password' => "committee",
                'role' => "Committee",
                'permission' => [
                    'view_game_timer',
                    'view_scoreboard',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 1",
                'email' => "puzzle.pos1@nplc.dev",
                'username' => 'puzzle.pos1',
                'password' => "lo#p.pos1",
                'role' => "LO Puzzle Pos 1",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 2a",
                'email' => "puzzle.pos2a@nplc.dev",
                'username' => 'puzzle.pos2a',
                'password' => "lo#p.pos2a",
                'role' => "LO Puzzle Pos 2a",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 2b",
                'email' => "puzzle.pos2b@nplc.dev",
                'username' => 'puzzle.pos2b',
                'password' => "lo#p.pos2b",
                'role' => "LO Puzzle Pos 2b",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 3a",
                'email' => "puzzle.pos3a@nplc.dev",
                'username' => 'puzzle.pos3a',
                'password' => "lo#p.pos3a",
                'role' => "LO Puzzle Pos 3a",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 3b",
                'email' => "puzzle.pos3b@nplc.dev",
                'username' => 'puzzle.pos3b',
                'password' => "lo#p.pos3b",
                'role' => "LO Puzzle Pos 3b",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 4a",
                'email' => "puzzle.pos4a@nplc.dev",
                'username' => 'puzzle.pos4a',
                'password' => "lo#p.pos4a",
                'role' => "LO Puzzle Pos 4a",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 4b",
                'email' => "puzzle.pos4b@nplc.dev",
                'username' => 'puzzle.pos4b',
                'password' => "lo#p.pos4b",
                'role' => "LO Puzzle Pos 4b",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Puzzle Pos 5",
                'email' => "puzzle.pos5@nplc.dev",
                'username' => 'puzzle.pos5',
                'password' => "lo#p.pos5",
                'role' => "LO Puzzle Pos 5",
                'permission' => [
                    'view_game_timer',
                    'start_pos_timer', 'stop_pos_timer', 'reset_pos_timer', 'view_pos_timer',
                    'assign_win', 'assign_lose', 'assign_middle', 'assign_forfeit',
                    'add_score', 'view_score',
                ]
            ],
            [
                'name' => "LO Rally Pos 1",
                'email' => "rally.pos1@nplc.dev",
                'username' => 'rally.pos1',
                'password' => "lo#r.pos1",
                'role' => "LO Rally Pos 1",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 2",
                'email' => "rally.pos2@nplc.dev",
                'username' => 'rally.pos2',
                'password' => "lo#r.pos2",
                'role' => "LO Rally Pos 2",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 3",
                'email' => "rally.pos3@nplc.dev",
                'username' => 'rally.pos3',
                'password' => "lo#r.pos3",
                'role' => "LO Rally Pos 3",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 4",
                'email' => "rally.pos4@nplc.dev",
                'username' => 'rally.pos4',
                'password' => "lo#r.pos4",
                'role' => "LO Rally Pos 4",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 5",
                'email' => "rally.pos5@nplc.dev",
                'username' => 'rally.pos5',
                'password' => "lo#r.pos5",
                'role' => "LO Rally Pos 5",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 6",
                'email' => "rally.pos6@nplc.dev",
                'username' => 'rally.pos6',
                'password' => "lo#r.pos6",
                'role' => "LO Rally Pos 6",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 7",
                'email' => "rally.pos7@nplc.dev",
                'username' => 'rally.pos7',
                'password' => "lo#r.pos7",
                'role' => "LO Rally Pos 7",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 8",
                'email' => "rally.pos8@nplc.dev",
                'username' => 'rally.pos8',
                'password' => "lo#r.pos8",
                'role' => "LO Rally Pos 8",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 9",
                'email' => "rally.pos9@nplc.dev",
                'username' => 'rally.pos9',
                'password' => "lo#r.pos9",
                'role' => "LO Rally Pos 9",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 10",
                'email' => "rally.pos10@nplc.dev",
                'username' => 'rally.pos10',
                'password' => "lo#r.pos10",
                'role' => "LO Rally Pos 10",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 11",
                'email' => "rally.pos11@nplc.dev",
                'username' => 'rally.pos11',
                'password' => "lo#r.pos11",
                'role' => "LO Rally Pos 11",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 12",
                'email' => "rally.pos12@nplc.dev",
                'username' => 'rally.pos12',
                'password' => "lo#r.pos12",
                'role' => "LO Rally Pos 12",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 13",
                'email' => "rally.pos13@nplc.dev",
                'username' => 'rally.pos13',
                'password' => "lo#r.pos13",
                'role' => "LO Rally Pos 13",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 14",
                'email' => "rally.pos14@nplc.dev",
                'username' => 'rally.pos14',
                'password' => "lo#r.pos14",
                'role' => "LO Rally Pos 14",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 15",
                'email' => "rally.pos15@nplc.dev",
                'username' => 'rally.pos15',
                'password' => "lo#r.pos15",
                'role' => "LO Rally Pos 15",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 16",
                'email' => "rally.pos16@nplc.dev",
                'username' => 'rally.pos16',
                'password' => "lo#r.pos16",
                'role' => "LO Rally Pos 16",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 17",
                'email' => "rally.pos17@nplc.dev",
                'username' => 'rally.pos17',
                'password' => "lo#r.pos17",
                'role' => "LO Rally Pos 17",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "LO Rally Pos 18",
                'email' => "rally.pos18@nplc.dev",
                'username' => 'rally.pos18',
                'password' => "lo#r.pos18",
                'role' => "LO Rally Pos 18",
                'permission' => [
                    'view_game_timer',
                    'assign_win', 'assign_lose',
                    'add_score', 'view_score',
                    'add_exp', 'view_exp',
                    'add_coin', 'view_coin',
                ]
            ],
            [
                'name' => "Player - test 1",
                'email' => "player.test1@nplc.dev",
                'username' => 'player.test1',
                'password' => "nplc2024#player-test1",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment',
                ]
            ],
            [
                'name' => "Player - test 2",
                'email' => "player.test2@nplc.dev",
                'username' => 'player.test2',
                'password' => "nplc2024#player-test2",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment',
                ]
            ],
            [
                'name' => "Player - test 3",
                'email' => "player.test3@nplc.dev",
                'username' => 'player.test3',
                'password' => "nplc2024#player-test3",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ]
            ],
            [
                'name' => "Player - test 4",
                'email' => "player.test4@nplc.dev",
                'username' => 'player.test4',
                'password' => "nplc2024#player-test4",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ]
            ],
            [
                'name' => "Player - test 5",
                'email' => "player.test5@nplc.dev",
                'username' => 'player.test5',
                'password' => "nplc2024#player-test5",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ]
            ],
            [
                'name' => "Player - test 6",
                'email' => "player.test6@nplc.dev",
                'username' => 'player.test6',
                'password' => "nplc2024#player-test6",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ]
            ],
            [
                'name' => "Player 1",
                'email' => "player1@nplc.dev",
                'username' => 'player1',
                'password' => "nplc2024#player1",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ]
            ],
            [
                'name' => "Player 2",
                'email' => "player2@nplc.dev",
                'username' => 'player2',
                'password' => "nplc2024#player2",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 3",
                'email' => "player3@nplc.dev",
                'username' => 'player3',
                'password' => "nplc2024#player3",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 4",
                'email' => "player4@nplc.dev",
                'username' => 'player4',
                'password' => "nplc2024#player4",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 5",
                'email' => "player5@nplc.dev",
                'username' => 'player5',
                'password' => "nplc2024#player5",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 6",
                'email' => "player6@nplc.dev",
                'username' => 'player6',
                'password' => "nplc2024#player6",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 7",
                'email' => "player7@nplc.dev",
                'username' => 'player7',
                'password' => "nplc2024#player7",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 8",
                'email' => "player8@nplc.dev",
                'username' => 'player8',
                'password' => "nplc2024#player8",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 9",
                'email' => "player9@nplc.dev",
                'username' => 'player9',
                'password' => "nplc2024#player9",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 10",
                'email' => "player10@nplc.dev",
                'username' => 'player10',
                'password' => "nplc2024#player10",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 11",
                'email' => "player11@nplc.dev",
                'username' => 'player11',
                'password' => "nplc2024#player11",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 12",
                'email' => "player12@nplc.dev",
                'username' => 'player12',
                'password' => "nplc2024#player12",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 13",
                'email' => "player13@nplc.dev",
                'username' => 'player13',
                'password' => "nplc2024#player13",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 14",
                'email' => "player14@nplc.dev",
                'username' => 'player14',
                'password' => "nplc2024#player14",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 15",
                'email' => "player15@nplc.dev",
                'username' => 'player15',
                'password' => "nplc2024#player15",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 16",
                'email' => "player16@nplc.dev",
                'username' => 'player16',
                'password' => "nplc2024#player16",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 17",
                'email' => "player17@nplc.dev",
                'username' => 'player17',
                'password' => "nplc2024#player17",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 18",
                'email' => "player18@nplc.dev",
                'username' => 'player18',
                'password' => "nplc2024#player18",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 19",
                'email' => "player19@nplc.dev",
                'username' => 'player19',
                'password' => "nplc2024#player19",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 20",
                'email' => "player20@nplc.dev",
                'username' => 'player20',
                'password' => "nplc2024#player20",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 21",
                'email' => "player21@nplc.dev",
                'username' => 'player21',
                'password' => "nplc2024#player21",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 22",
                'email' => "player22@nplc.dev",
                'username' => 'player22',
                'password' => "nplc2024#player22",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 23",
                'email' => "player23@nplc.dev",
                'username' => 'player23',
                'password' => "nplc2024#player23",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 24",
                'email' => "player24@nplc.dev",
                'username' => 'player24',
                'password' => "nplc2024#player24",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 25",
                'email' => "player25@nplc.dev",
                'username' => 'player25',
                'password' => "nplc2024#player25",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 26",
                'email' => "player26@nplc.dev",
                'username' => 'player26',
                'password' => "nplc2024#player26",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 27",
                'email' => "player27@nplc.dev",
                'username' => 'player27',
                'password' => "nplc2024#player27",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 28",
                'email' => "player28@nplc.dev",
                'username' => 'player28',
                'password' => "nplc2024#player28",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 29",
                'email' => "player29@nplc.dev",
                'username' => 'player29',
                'password' => "nplc2024#player29",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 30",
                'email' => "player30@nplc.dev",
                'username' => 'player30',
                'password' => "nplc2024#player30",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 31",
                'email' => "player31@nplc.dev",
                'username' => 'player31',
                'password' => "nplc2024#player31",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 32",
                'email' => "player32@nplc.dev",
                'username' => 'player32',
                'password' => "nplc2024#player32",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 33",
                'email' => "player33@nplc.dev",
                'username' => 'player33',
                'password' => "nplc2024#player33",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 34",
                'email' => "player34@nplc.dev",
                'username' => 'player34',
                'password' => "nplc2024#player34",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 35",
                'email' => "player35@nplc.dev",
                'username' => 'player35',
                'password' => "nplc2024#player35",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 36",
                'email' => "player36@nplc.dev",
                'username' => 'player36',
                'password' => "nplc2024#player36",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 37",
                'email' => "player37@nplc.dev",
                'username' => 'player37',
                'password' => "nplc2024#player37",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 38",
                'email' => "player38@nplc.dev",
                'username' => 'player38',
                'password' => "nplc2024#player38",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],[
                'name' => "Player 39",
                'email' => "player39@nplc.dev",
                'username' => 'player39',
                'password' => "nplc2024#player39",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
            [
                'name' => "Player 40",
                'email' => "player40@nplc.dev",
                'username' => 'player40',
                'password' => "nplc2024#player40",
                'role' => "Player",
                'permission' => [
                    'view_game_timer',
                    'view_pos_timer',
                    'view_scoreboard', 'edit_scoreboard',
                    'view_story',
                    'view_item',
                    'view_score', 'view_exp', 'view_coin',
                    'buy_equipment', 'use_equipment', 'view_equipment',
                ],
            ],
        ];

        foreach ($users as $user) {
            User::create([
                'name' => $user['name'],
                'email' => $user['email'],
                'email_verified_at' => now(),
                'username' => $user['username'],
                'password' => Hash::make($user['password']),
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
            ])->assignRole($user['role'])->givePermissionTo($user['permission']);
        }
    }
}
